In [39]:
%matplotlib inline
import pandas as pd
import matplotlib.pyplot as plt

In [40]:
airbnb_NY = pd.read_csv("../data/Airbnb_NYC.csv")

#### Solution $1$ using `loc` method:

In [41]:
for borough in airbnb_NY["Boroughs"].unique():
    top_10 = airbnb_NY.loc[airbnb_NY["Boroughs"] == borough].sort_values("Reviews30d", ascending=False)[:10]
    print(borough, top_10["Price"].mean())

Bronx 99.4
Brooklyn 79.6
Manhattan 108.6
Queens 52.8
Staten Island 84.8

#### Solution $2$ using `groupby` method:

In [42]:
def return_groupby_values(x):
    return x

In [43]:
airbnb_NY.groupby(['Boroughs'])[['Boroughs', 'Reviews30d', 'Price']].apply(return_groupby_values)

                          Boroughs  Reviews30d  Price
Boroughs
Bronx         0              Bronx        0.27   60.0
              1              Bronx        2.93   49.0
              2              Bronx        0.87   50.0
              3              Bronx        0.36   71.0
              4              Bronx        3.50  115.0
...                            ...         ...    ...
Staten Island 38728  Staten Island        4.73  130.0
              38729  Staten Island        1.05   43.0
              38730  Staten Island        1.35  105.0
              38731  Staten Island        1.88  135.0
              38732  Staten Island        2.32  140.0

[38733 rows x 3 columns]

#### `lambda` function

In [49]:
df_ratings = airbnb_NY.groupby(['Boroughs'])[['Boroughs', 'Reviews30d', 'Price']].apply(lambda x: x)

df_ratings

                          Boroughs  Reviews30d  Price
Boroughs
Bronx         0              Bronx        0.27   60.0
              1              Bronx        2.93   49.0
              2              Bronx        0.87   50.0
              3              Bronx        0.36   71.0
              4              Bronx        3.50  115.0
...                            ...         ...    ...
Staten Island 38728  Staten Island        4.73  130.0
              38729  Staten Island        1.05   43.0
              38730  Staten Island        1.35  105.0
              38731  Staten Island        1.88  135.0
              38732  Staten Island        2.32  140.0

[38733 rows x 3 columns]

In [54]:
df_ratings_boroughs = df_ratings.loc[df_ratings['Boroughs']=='Bronx']

df_ratings_boroughs

             Boroughs  Reviews30d  Price
Boroughs
Bronx    0      Bronx        0.27   60.0
         1      Bronx        2.93   49.0
         2      Bronx        0.87   50.0
         3      Bronx        0.36   71.0
         4      Bronx        3.50  115.0
...               ...         ...    ...
         886    Bronx        0.48   59.0
         887    Bronx        1.44  120.0
         888    Bronx        2.00   65.0
         889    Bronx        2.13   53.0
         890    Bronx        1.00   60.0

[891 rows x 3 columns]

In [57]:
df_ratings_boroughs_top_ten = df_ratings_boroughs.sort_values("Reviews30d", ascending=False)[:10]

df_ratings_boroughs_top_ten

             Boroughs  Reviews30d  Price
Boroughs
Bronx    265    Bronx       10.41   95.0
         576    Bronx        9.62   60.0
         752    Bronx        9.00   57.0
         122    Bronx        8.44   85.0
         879    Bronx        8.31   34.0
         44     Bronx        8.05   95.0
         185    Bronx        7.43   75.0
         877    Bronx        7.18   55.0
         884    Bronx        7.00  288.0
         339    Bronx        6.98  150.0

In [58]:
df_ratings_boroughs_top_ten['Price'].mean()

np.float64(99.4)